#' Calculate Phylogenetic Diversity
#'
#' This function calculates the phylogenetic diversity (PD) for a given dataset and phylogenetic tree.
#'
#' @param Fin A data frame or data table containing species presence data. The data should include columns for `species`, `cell`, and `Landuse`.
#' @param Tree A phylogenetic tree object, typically generated by the `V.PhyloMaker::phylo.maker` function. The tree must contain a component named `scenario.3` with the tip labels.
#' @return A data table containing the calculated phylogenetic diversity (PD) for each cell, along with the associated `cell` and `Landuse`.
#' @examples
#' \dontrun{
#'   # Example usage:
#'   Fin <- data.table(
#'     cell = c(1, 1, 2, 2),
#'     species = c("species_a", "species_b", "species_a", "species_c"),
#'     Landuse = c("forest", "forest", "grassland", "grassland")
#'   )
#'
#'   # Assume this generates a valid tree object
#'   Tree <- V.PhyloMaker::phylo.maker(...)
#'
#'   # Calculate phylogenetic diversity
#'   pd_results <- calc_pd(Fin, Tree)
#'   print(pd_results)
#' }

#' @import data.table
#' @importFrom stringr str_replace_all
#' @importFrom picante pd
#' @export
calc_pd <- function(Fin, Tree){

  Pres <- species <- NULL

  Fin <- as.data.table(Fin)
  Leaves <- Tree$scenario.3$tip.label
  Landuse <- unique(Fin$Landuse)
  Fin[, Pres := 1]
  Fin[, species := stringr::str_replace_all(species, " ", "_")]

  Fin2 <- data.table::dcast(Fin, cell ~ species, value.var = "Pres", fill = 0)
  Index <- which(colnames(Fin2) %in% Leaves)
  Mat <- as.matrix(Fin2)[, Index]

  PD <- picante::pd(samp = Mat, Tree$scenario.3, include.root = FALSE) |>
    as.data.table()
  PD[, PD := ifelse(is.na(PD), 0 , PD)]

  PD$cell <- Fin2$cell
  PD$Landuse <- Landuse
  as.data.frame(PD)
  return(PD)
}
