#' Generate a Land-Use Suitability Table
#'
#' This function takes the path to a raster file containing land-use suitability values and converts it to a data frame. It filters the data to include only the cells that have a value of 1 in at least one of the land-use categories, indicating suitability.
#'
#' @param path A string representing the file path to the raster file containing land-use suitability data.
#'
#' @return A data frame with the raster cells that have a suitability value of 1 in at least one of the land-use categories. The data frame includes the `cell` identifier and the corresponding suitability values for each land-use category.
#'
#' @importFrom terra rast as.data.frame
#' @importFrom dplyr filter across
#'
#' @examples
#' # Get path for habitat suitability raster
#' HabSut <- system.file("ex/HabSut.tif", package = "SpeciesPoolR")
#'
#' # Use the function to get the data frame
#' generate_landuse_table(path = HabSut)
#'
#' @export
generate_landuse_table <- function(path) {
  DF <- terra::rast(path) |>
    terra::as.data.frame(cells = TRUE) |>
    dplyr::filter(rowSums(dplyr::across(-cell, ~. == 1)) > 0)
  return(DF)
}

#' Generate and Transform a Land-Use Suitability Table
#'
#' This function takes the path to a raster file containing land-use suitability values, converts it to a data frame, and filters it to include only the cells that have a value of 1 in at least one of the land-use categories. It then transforms the filtered data into a long-format table where each row corresponds to a specific cell and habitat type.
#'
#' @param path A string representing the file path to the raster file containing land-use suitability data.
#'
#' @return A data frame in long format with the raster cells that have a suitability value of 1 in at least one of the land-use categories. The data frame includes the `cell` identifier and the corresponding habitat types (`Habitat`) where suitability is 1.
#'
#' @importFrom terra rast as.data.frame
#' @importFrom dplyr filter across
#' @importFrom data.table as.data.table melt
#'
#' @examples
#' # Get path for habitat suitability raster
#' HabSut <- system.file("ex/HabSut.tif", package = "SpeciesPoolR")
#'
#' # Use the function to generate and transform the land-use suitability table
#' generate_long_landuse_table(path = HabSut)
#'
#' @export
generate_long_landuse_table <- function(path) {
  # Convert raster to data frame and filter for cells with at least one suitability value of 1
  DF <- terra::rast(path) |>
    terra::as.data.frame(cells = TRUE) |>
    dplyr::filter(rowSums(dplyr::across(-cell, ~. == 1)) > 0)

  # Convert to data.table and reshape to long format
  DF <- as.data.table(DF) |>
    melt(id.vars = "cell",
         measure.vars = c("ForestDryPoor", "ForestDryRich", "ForestWetPoor", "ForestWetRich", "OpenDryPoor", "OpenDryRich", "OpenWetPoor", "OpenWetRich"),
         variable.name = "Habitat",
         value.name = "Suitability", na.rm = TRUE)

  # Filter out rows where Suitability is 0 or less
  DF <- DF[Suitability > 0]

  # Remove the Suitability column and convert back to a data frame
  DF <- DF[, Suitability := NULL]
  DF <- as.data.frame(DF)

  return(DF)
}

#' Filter Species Presences by Habitat Suitability
#'
#' This function takes a long-format land-use table, a buffer data frame of species presences, and a lookup table to determine which species can thrive in which habitats. It filters the species presences to include only those cells that are both within the species' buffer zones and have suitable habitats according to the lookup table.
#'
#' @param Long_LU_table A long-format data frame containing land-use suitability data, as generated by `generate_long_landuse_table`.
#' @param Long_Buffer_gbif A data frame containing the buffer zones for species presences, typically generated earlier in the workflow.
#' @param LookUpTable A data frame containing the lookup table that maps species to suitable habitats.
#'
#' @return A data table with the filtered species presences. The returned data table includes the `cell` identifier and the corresponding `species` that can thrive in that cell based on the habitat suitability.
#'
#' @importFrom data.table as.data.table %chin%
#' @importFrom dplyr mutate
#'
#' @examples
#' # Assuming you have the following objects from previous steps:
#' # Long_LU_table - The long-format land-use suitability table
#' # Long_Buffer_gbif - The buffer data frame of species presences
#' # LookUpTable - The lookup table mapping species to suitable habitats
#'
#' final_presences <- make_final_presences(Long_LU_table, Long_Buffer_gbif, LookUpTable)
#'
#' @export
make_final_presences <- function(Long_LU_table, Long_Buffer_gbif, LookUpTable) {
  if (nrow(Long_Buffer_gbif) == 0) {
    result2 <- data.frame(matrix(ncol = 3, nrow = 0))
    colnames(result2) <- c("cell", "species", "Landuse")
    result2 <- result2 |> dplyr::mutate(cell = as.integer(cell),
                                        species = as.character(species),
                                        Landuse = as.character(Landuse))
    result2 <- as.data.table(result2)
  } else {

    # Modify Long_LU_table
    Long_LU_table <- as.data.table(Long_LU_table)
    Long_LU_table[, Habitat := as.character(Habitat)]

    # Check feasible habitats for the particular species
    Feasible_Landuses <- LookUpTable[species %chin% unique(Long_Buffer_gbif$species)]

    # Transform Landuse into habitat and remove the prefix
    Feasible_Landuses[, Habitat := Landuse]
    Feasible_Landuses[, Pres := NULL]
    Feasible_Landuses <- Feasible_Landuses[Landuse != "Exclude"]

    # Get only the cells that can become the feasible Landuses
    Available_Cells <- Long_LU_table[Habitat %chin% unique(Feasible_Landuses$Habitat)]

    # Check which of the available cells for the species can be in a habitat suitable for the species
    FeasibleCells <- Long_Buffer_gbif[cell %chin% unique(Available_Cells$cell)]

    # Join all three data.tables
    result <- FeasibleCells[Available_Cells, on = "cell", nomatch = 0]
    result2 <- result[Feasible_Landuses, on = .(Habitat, species), nomatch = 0, allow.cartesian = TRUE]
    result2[, Habitat := NULL]
  }

  # Return the final result
  return(result2)
}
