#' Generate Phylogenetic Tree
#'
#' This function takes a CSV file path, reads the data, and generates a phylogenetic tree using the `V.PhyloMaker` package.
#'
#' @param DF A character string specifying the file path to a CSV file. The CSV file must contain columns named `species`, `genus`, and `family`.
#' @return A phylogenetic tree object generated by the `V.PhyloMaker::phylo.maker` function.
#' @examples
#' \dontrun{
#'   # Example usage:
#'   p <- system.file("ex/Clean_Species.csv", package="SpeciesPoolR")
#'   tree <- generate_tree(p)
#'
#' }
#' @importFrom readr read_csv
#' @importFrom dplyr select distinct
#' @importFrom V.PhyloMaker phylo.maker
#' @export
generate_tree <- function(DF){

  species <- genus <- family <- NULL

  Tree <- readr::read_csv(DF) |>
    dplyr::select(species, genus, family) |>
    dplyr::distinct() |>
    V.PhyloMaker::phylo.maker(tree = V.PhyloMaker::GBOTB.extended, nodes = V.PhyloMaker::nodes.info.1)
  return(Tree)
}
