# Internal helpers used by the targets script generated by run_workflow().
# They deliberately remain small orchestration helpers: the ecological
# calculations themselves live in the exported SpeciesPoolR functions.

.workflow_supported_groups <- c(
  "amphibian",
  "bee",
  "bird",
  "butterfly",
  "fish",
  "mammal",
  "plant",
  "reptile",
  "shark_ray"
)

.workflow_terrestrial_groups <- c(
  "plant",
  "bird",
  "mammal",
  "amphibian",
  "reptile",
  "bee",
  "butterfly"
)

.workflow_marine_mammal_families <- c(
  "Balaenidae",
  "Balaenopteridae",
  "Delphinidae",
  "Eschrichtiidae",
  "Iniidae",
  "Kogiidae",
  "Lipotidae",
  "Monodontidae",
  "Neobalaenidae",
  "Phocoenidae",
  "Physeteridae",
  "Platanistidae",
  "Pontoporiidae",
  "Ziphiidae",
  "Dugongidae",
  "Trichechidae",
  "Odobenidae",
  "Otariidae",
  "Phocidae"
)

.workflow_marine_mammal_orders <- c(
  "Cetacea",
  "Sirenia",
  "Pinnipedia"
)

.workflow_assert_scalar_integer <- function(x, argument, minimum = 1L) {
  if (
    !is.numeric(x) ||
      length(x) != 1L ||
      is.na(x) ||
      !is.finite(x) ||
      x != floor(x) ||
      x < minimum
  ) {
    stop(
      "`", argument, "` must be one integer of at least ", minimum, ".",
      call. = FALSE
    )
  }

  as.integer(x)
}

.workflow_prepare_taxa <- function(file) {
  x <- SpeciesPoolR::get_data(file)
  lower_names <- tolower(names(x))
  required <- c(
    "species",
    "genus",
    "family",
    "kingdom",
    "class",
    "gbif_specieskey"
  )

  if (!all(required %in% lower_names)) {
    species_index <- match("species", lower_names)
    if (is.na(species_index)) {
      species_index <- match("taxa", lower_names)
    }
    if (is.na(species_index)) {
      stop(
        "The taxon file must either be a cleaned SpeciesPoolR table or ",
        "contain a `Species` column.",
        call. = FALSE
      )
    }

    x <- SpeciesPoolR::Clean_Taxa(
      unique(as.character(x[[species_index]]))
    )
    lower_names <- tolower(names(x))
  }

  canonical_names <- c(
    "species",
    "genus",
    "family",
    "kingdom",
    "phylum",
    "class",
    "order",
    "gbif_speciesKey"
  )
  for (canonical in canonical_names) {
    index <- match(tolower(canonical), tolower(names(x)))
    if (!is.na(index)) {
      names(x)[[index]] <- canonical
    }
  }

  required_after_cleaning <- c(
    "species",
    "genus",
    "family",
    "kingdom",
    "class",
    "gbif_speciesKey"
  )
  missing <- setdiff(required_after_cleaning, names(x))
  if (length(missing) > 0L) {
    stop(
      "The cleaned taxon table is missing: ",
      paste(missing, collapse = ", "),
      ".",
      call. = FALSE
    )
  }

  if (!"order" %in% names(x)) {
    x$order <- NA_character_
  }

  x$rtrees_group <- SpeciesPoolR::classify_rtrees_group(x)
  x <- x[
    !is.na(x$species) & nzchar(as.character(x$species)),
    ,
    drop = FALSE
  ]
  x <- x[!duplicated(as.character(x$species)), , drop = FALSE]
  rownames(x) <- NULL
  x
}

.workflow_apply_scope <- function(
    x,
    groups,
    terrestrial_only = TRUE) {
  groups <- unique(as.character(groups))
  out <- x[
    !is.na(x$rtrees_group) & x$rtrees_group %in% groups,
    ,
    drop = FALSE
  ]

  if (isTRUE(terrestrial_only)) {
    family <- tolower(trimws(as.character(out$family)))
    order <- tolower(trimws(as.character(out$order)))
    marine_families <- tolower(.workflow_marine_mammal_families)
    marine_orders <- tolower(.workflow_marine_mammal_orders)

    marine <-
      out$rtrees_group %in% c("fish", "shark_ray") |
      family %in% marine_families |
      order %in% marine_orders
    out <- out[!marine, , drop = FALSE]
  }

  required_values <-
    !is.na(out$genus) & nzchar(as.character(out$genus)) &
    !is.na(out$family) & nzchar(as.character(out$family)) &
    !is.na(out$gbif_speciesKey)
  out <- out[required_values, , drop = FALSE]
  rownames(out) <- NULL
  out
}

.workflow_systematic_group_sample <- function(
    x,
    groups,
    number_per_group = Inf) {
  if (is.infinite(number_per_group)) {
    out <- x[order(
      match(x$rtrees_group, groups),
      x$N,
      x$species
    ), , drop = FALSE]
    out$selection_rank <- ave(
      seq_len(nrow(out)),
      out$rtrees_group,
      FUN = seq_along
    )
    rownames(out) <- NULL
    return(out)
  }

  number_per_group <- .workflow_assert_scalar_integer(
    number_per_group,
    "number_per_group"
  )

  selected <- lapply(groups, function(group_name) {
    candidates <- x[
      as.character(x$rtrees_group) == group_name,
      ,
      drop = FALSE
    ]
    candidates <- candidates[order(
      candidates$N,
      candidates$species
    ), , drop = FALSE]

    if (nrow(candidates) == 0L) {
      return(candidates)
    }

    number_to_take <- min(number_per_group, nrow(candidates))
    index <- unique(as.integer(round(seq(
      from = 1,
      to = nrow(candidates),
      length.out = number_to_take
    ))))
    out <- candidates[index, , drop = FALSE]
    out$selection_rank <- seq_len(nrow(out))
    out
  })

  out <- dplyr::bind_rows(selected)
  out <- out[order(
    match(out$rtrees_group, groups),
    out$selection_rank,
    out$species
  ), , drop = FALSE]
  rownames(out) <- NULL
  out
}

.workflow_get_presences_with_retry <- function(
    species,
    country = NULL,
    shapefile = NULL,
    limit = 5000L,
    retries = 5L) {
  last_error <- NULL

  for (attempt in seq_len(retries)) {
    result <- tryCatch(
      SpeciesPoolR::get_presences(
        species,
        country = country,
        shapefile = shapefile,
        limit = limit
      ),
      error = function(e) {
        last_error <<- e
        NULL
      }
    )

    if (is.data.frame(result) && nrow(result) > 0L) {
      return(result)
    }

    if (attempt < retries) {
      wait <- min(60, 2^(attempt - 1L) + stats::runif(1L, 0, 1))
      message(
        "No usable GBIF download for ", species,
        " (attempt ", attempt, " of ", retries,
        "). Retrying in ", round(wait, 1), " seconds."
      )
      Sys.sleep(wait)
    }
  }

  detail <- if (is.null(last_error)) {
    "GBIF returned no usable records."
  } else {
    conditionMessage(last_error)
  }
  stop(
    "GBIF download failed for ", species,
    " after ", retries, " attempts. ", detail,
    call. = FALSE
  )
}

.workflow_validate_presence_data <- function(
    x,
    expected_species,
    minimum_records = 7L) {
  required <- c(
    "species",
    "family",
    "genus",
    "decimalLongitude",
    "decimalLatitude"
  )
  if (!is.data.frame(x) || !all(required %in% names(x))) {
    stop(
      "GBIF returned no usable table for ", expected_species, ".",
      call. = FALSE
    )
  }

  keep <-
    as.character(x$species) == expected_species &
    !is.na(x$family) &
    !is.na(x$genus) &
    is.finite(x$decimalLongitude) &
    is.finite(x$decimalLatitude) &
    x$decimalLongitude >= -180 &
    x$decimalLongitude <= 180 &
    x$decimalLatitude >= -90 &
    x$decimalLatitude <= 90
  out <- x[keep, , drop = FALSE]
  duplicate_key <- paste(
    out$species,
    out$decimalLongitude,
    out$decimalLatitude,
    sep = "\r"
  )
  out <- out[!duplicated(duplicate_key), , drop = FALSE]
  rownames(out) <- NULL

  if (nrow(out) < minimum_records) {
    stop(
      expected_species, " has only ", nrow(out),
      " valid unique records; at least ", minimum_records,
      " are required.",
      call. = FALSE
    )
  }
  out
}

.workflow_validate_presence_branches <- function(
    raw,
    species,
    minimum_records) {
  valid <- Map(
    function(x, species_name) {
      tryCatch(
        .workflow_validate_presence_data(
          x,
          expected_species = species_name,
          minimum_records = minimum_records
        ),
        error = function(e) {
          warning(
            "Skipping ", species_name, ": ", conditionMessage(e),
            call. = FALSE,
            immediate. = TRUE
          )
          NULL
        }
      )
    },
    raw,
    species
  )
  keep <- !vapply(valid, is.null, logical(1L))
  valid <- valid[keep]
  names(valid) <- as.character(species[keep])
  valid
}

.workflow_presence_audit <- function(raw, species, valid_presences, taxa) {
  downloaded <- vapply(
    raw,
    function(x) if (is.data.frame(x)) nrow(x) else 0L,
    integer(1L)
  )
  retained <- names(valid_presences)
  out <- data.frame(
    species = as.character(species),
    downloaded_records = downloaded,
    retained = as.character(species) %in% retained,
    stringsAsFactors = FALSE
  )
  out$status <- ifelse(
    out$retained,
    "retained",
    ifelse(
      out$downloaded_records == 0L,
      "download_failed_or_empty",
      "failed_validation"
    )
  )
  group_index <- match(out$species, as.character(taxa$species))
  out$rtrees_group <- as.character(taxa$rtrees_group[group_index])
  out
}

.workflow_safe_species_id <- function(species) {
  species <- as.character(species[[1L]])
  stem <- gsub("[^A-Za-z0-9]+", "_", species)
  stem <- gsub("^_+|_+$", "", stem)
  if (!nzchar(stem)) {
    stem <- "species"
  }

  code_points <- utf8ToInt(enc2utf8(species))
  checksum <- sum(
    as.double(code_points) * seq_along(code_points)
  ) %% 2147483647
  paste0(stem, "_", sprintf("%08x", as.integer(checksum)))
}

.workflow_species_file_index <- function(species) {
  species <- unique(as.character(species))
  species <- species[!is.na(species) & nzchar(species)]
  ids <- vapply(species, .workflow_safe_species_id, character(1L))
  duplicated_ids <- unique(ids[duplicated(ids)])
  if (length(duplicated_ids) > 0L) {
    stop(
      "Species file-name collision detected for: ",
      paste(species[ids %in% duplicated_ids], collapse = ", "),
      ".",
      call. = FALSE
    )
  }

  data.frame(
    species = species,
    species_id = unname(ids),
    stringsAsFactors = FALSE
  )
}

.workflow_single_species_name <- function(models, allow_null = FALSE) {
  valid <-
    is.list(models) &&
    length(models) == 1L &&
    !is.null(names(models)) &&
    length(names(models)) == 1L &&
    !is.na(names(models)[[1L]]) &&
    nzchar(names(models)[[1L]])
  if (!valid) {
    stop("Each branch must receive one named species model.", call. = FALSE)
  }

  species <- names(models)[[1L]]
  if (is.null(models[[1L]]) && !isTRUE(allow_null)) {
    stop("The fitted model is NULL for ", species, ".", call. = FALSE)
  }
  species
}

.workflow_normalise_path <- function(path) {
  out <- normalizePath(path, winslash = "/", mustWork = FALSE)
  if (.Platform$OS.type == "windows") {
    out <- tolower(out)
  }
  out
}

.workflow_temporary_raster_sources <- function(...) {
  rasters <- list(...)
  paths <- unique(unlist(lapply(rasters, function(x) {
    if (inherits(x, "SpatRaster")) {
      as.character(terra::sources(x))
    } else {
      character()
    }
  }), use.names = FALSE))
  paths <- paths[!is.na(paths) & nzchar(paths)]
  if (length(paths) == 0L) {
    return(character())
  }

  terra_options <- terra::terraOptions(print = FALSE)
  temporary_roots <- unique(c(tempdir(), terra_options$tempdir))
  temporary_roots <- temporary_roots[
    !is.na(temporary_roots) & nzchar(temporary_roots)
  ]
  normal_paths <- .workflow_normalise_path(paths)
  normal_roots <- .workflow_normalise_path(temporary_roots)
  inside <- vapply(normal_paths, function(path) {
    any(vapply(normal_roots, function(root) {
      identical(path, root) || startsWith(path, paste0(root, "/"))
    }, logical(1L)))
  }, logical(1L))
  unique(paths[inside])
}

.workflow_remove_temporary_rasters <- function(paths) {
  paths <- unique(as.character(paths))
  paths <- paths[!is.na(paths) & nzchar(paths) & file.exists(paths)]
  if (length(paths) > 0L) {
    unlink(paths, force = TRUE)
  }
  invisible(NULL)
}

.workflow_assert_real_prediction <- function(suitability, species) {
  sources <- as.character(terra::sources(suitability))
  if (any(grepl(
    "SpeciesPoolR_zero_suitability_",
    basename(sources),
    fixed = TRUE
  ), na.rm = TRUE)) {
    stop(
      "SpeciesPoolR returned its zero-raster error fallback for ",
      species, ".",
      call. = FALSE
    )
  }
  invisible(suitability)
}

.workflow_write_binary_raster <- function(binary, path) {
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  terra::writeRaster(
    binary,
    filename = path,
    overwrite = TRUE,
    wopt = list(
      datatype = "INT1U",
      NAflag = 255,
      gdal = c("COMPRESS=DEFLATE", "TILED=YES")
    )
  )
  path
}

.workflow_summarise_projection <- function(suitability, binary, scenario) {
  suitability_stats <- terra::global(
    suitability,
    fun = c("mean", "min", "max"),
    na.rm = TRUE
  )
  occupied_cells <- terra::global(binary, fun = "sum", na.rm = TRUE)

  if (
    nrow(suitability_stats) != 1L ||
      any(!is.finite(as.matrix(suitability_stats))) ||
      nrow(occupied_cells) != 1L ||
      !is.finite(occupied_cells$sum[[1L]])
  ) {
    stop("Projection summary contains non-finite values.", call. = FALSE)
  }

  data.frame(
    scenario = scenario,
    species = names(suitability)[[1L]],
    suitability_mean = suitability_stats$mean[[1L]],
    suitability_min = suitability_stats$min[[1L]],
    suitability_max = suitability_stats$max[[1L]],
    predicted_cells_Thres_95 = occupied_cells$sum[[1L]],
    stringsAsFactors = FALSE
  )
}

.workflow_project_current_species <- function(
    models,
    presences,
    buffer,
    predictors,
    categorical,
    output_root,
    blocks_in_memory = 16L,
    minimum_complete_presences = 7L) {
  species <- .workflow_single_species_name(models, allow_null = TRUE)
  species_id <- .workflow_safe_species_id(species)
  output_directory <- file.path(output_root, "current")
  dir.create(output_directory, recursive = TRUE, showWarnings = FALSE)

  binary_path <- file.path(
    output_directory,
    paste0(species_id, "_binary.tif")
  )
  threshold_path <- file.path(
    output_directory,
    paste0(species_id, "_threshold.rds")
  )
  summary_path <- file.path(
    output_directory,
    paste0(species_id, "_summary.csv")
  )
  status_path <- file.path(
    output_directory,
    paste0(species_id, "_status.csv")
  )

  scratch_paths <- character()
  on.exit(.workflow_remove_temporary_rasters(scratch_paths), add = TRUE)
  write_status <- function(record) {
    SpeciesPoolR::write_projection_status(record, status_path)
    status_path
  }

  if (is.null(models[[1L]])) {
    record <- SpeciesPoolR::projection_status_record(
      species = species,
      scenario = "current",
      status = "model_failed",
      reason = "FitSpeciesModels() returned NULL."
    )
    write_status(record)
    return(c(status = status_path))
  }

  tryCatch({
    if (!is.data.frame(presences)) {
      stop("`presences` must be a data frame.", call. = FALSE)
    }
    if (!inherits(buffer, "SpatVector")) {
      stop("`buffer` must be a terra SpatVector.", call. = FALSE)
    }
    if (!identical(unique(as.character(presences$species)), species)) {
      stop("Presence data and model species do not match.", call. = FALSE)
    }

    complete_presences <- SpeciesPoolR::SampleEnv(
      DF = presences,
      file = predictors,
      categorical = categorical,
      type = "pres"
    )
    number_complete <- nrow(complete_presences)

    suitability <- SpeciesPoolR::PredictSuitability(
      Models = models,
      file = predictors,
      categorical = categorical,
      blocks_in_memory = blocks_in_memory
    )
    scratch_paths <- unique(c(
      scratch_paths,
      .workflow_temporary_raster_sources(suitability)
    ))
    .workflow_assert_real_prediction(suitability, species)

    thresholds <- SpeciesPoolR::create_thresholds(
      Model = suitability,
      reference = presences
    )
    assessment <- SpeciesPoolR::assess_projection_status(
      suitability = suitability,
      thresholds = thresholds,
      species = species,
      scenario = "current",
      threshold = "Thres_95",
      complete_presence_records = number_complete,
      minimum_complete_presences = minimum_complete_presences
    )

    if (!identical(assessment$status[[1L]], "projected")) {
      write_status(assessment)
      rm(suitability)
      invisible(gc())
      .workflow_remove_temporary_rasters(scratch_paths)
      scratch_paths <- character()
      return(c(status = status_path))
    }

    masked <- SpeciesPoolR::mask_suitability(
      Model = suitability,
      Mask = buffer
    )
    scratch_paths <- unique(c(
      scratch_paths,
      .workflow_temporary_raster_sources(masked)
    ))
    binary <- SpeciesPoolR::threshold_suitability(
      Model = masked,
      Thresholds = thresholds,
      threshold = "Thres_95"
    )
    scratch_paths <- unique(c(
      scratch_paths,
      .workflow_temporary_raster_sources(binary)
    ))

    summary <- .workflow_summarise_projection(
      suitability,
      binary,
      scenario = "current"
    )
    summary$binary_path <- binary_path

    .workflow_write_binary_raster(binary, binary_path)
    saveRDS(thresholds, threshold_path)
    readr::write_csv(summary, summary_path)
    completed <- SpeciesPoolR::projection_status_record(
      species = species,
      scenario = "current",
      status = "projected",
      binary_path = binary_path,
      threshold_path = threshold_path,
      summary_path = summary_path,
      finite_cells = assessment$finite_cells[[1L]],
      complete_presence_records = number_complete
    )
    write_status(completed)

    rm(suitability, masked, binary)
    invisible(gc())
    .workflow_remove_temporary_rasters(scratch_paths)
    scratch_paths <- character()

    c(
      binary = binary_path,
      threshold = threshold_path,
      summary = summary_path,
      status = status_path
    )
  }, error = function(e) {
    unlink(c(binary_path, threshold_path, summary_path), force = TRUE)
    failed <- SpeciesPoolR::projection_status_record(
      species = species,
      scenario = "current",
      status = "prediction_error",
      reason = conditionMessage(e)
    )
    write_status(failed)
    c(status = status_path)
  })
}

.workflow_collect_product_files <- function(products, suffix) {
  paths <- unname(unlist(products, use.names = FALSE))
  paths <- paths[
    !is.na(paths) &
      nzchar(paths) &
      endsWith(paths, suffix)
  ]
  unique(paths)
}

.workflow_read_projection_summaries <- function(products) {
  paths <- .workflow_collect_product_files(products, "_summary.csv")
  if (length(paths) == 0L) {
    return(data.frame(
      scenario = character(),
      species = character(),
      suitability_mean = double(),
      suitability_min = double(),
      suitability_max = double(),
      predicted_cells_Thres_95 = double(),
      binary_path = character(),
      stringsAsFactors = FALSE
    ))
  }

  dplyr::bind_rows(lapply(paths, function(path) {
    readr::read_csv(
      path,
      show_col_types = FALSE,
      progress = FALSE
    )
  }))
}

.workflow_raster_output_path <- function(x, expected_path) {
  rm(x)
  invisible(gc())
  if (!file.exists(expected_path)) {
    stop("Expected raster was not written: ", expected_path, call. = FALSE)
  }
  expected_path
}

#' Run a file-backed SpeciesPoolR diversity workflow
#'
#' Creates and runs a `targets` pipeline for a current-condition biodiversity
#' analysis. The generated pipeline cleans and scopes taxa, counts and downloads
#' GBIF occurrences, fits one model per species, writes reason-coded projection
#' status markers, validates the complete projection set, and calculates
#' richness, range-size rarity, and group-specific phylogenetic diversity.
#'
#' The workflow follows the bounded-memory design used for large SpeciesPoolR
#' analyses: successful species branches write one binary GeoTIFF each;
#' richness and rarity use tree reductions; PD reads raster blocks into sparse
#' matrices; and no complete cells-by-species raster stack is materialized.
#'
#' `rtrees` phylogenies are built separately for each supported group. Raw PD
#' values therefore retain the branch-length scale of their own group tree and
#' should not be summed or directly compared among groups without an explicit
#' normalization step.
#'
#' @param file_path CSV or XLSX taxon file. A table already returned by
#'   [Clean_Taxa()] is preferred. A simpler file with a case-insensitive
#'   `Species` column is cleaned automatically.
#' @param predictors Character vector of current-condition raster paths. Every
#'   layer must share a common geometry. Supply categorical layer names through
#'   `categorical`.
#' @param country Two-letter country code used for GBIF queries. Supply exactly
#'   one of `country` and `shapefile`.
#' @param shapefile Optional vector-file path used as the GBIF query extent.
#'   Supply exactly one of `country` and `shapefile`.
#' @param filter Optional unquoted or `quote()`d expression evaluated on the
#'   cleaned taxon table after `rtrees_group` has been added. Taxonomic column
#'   names are lower case.
#' @param groups rtrees groups retained in the analysis. The default contains
#'   the seven groups used by the terrestrial diversity pilot.
#' @param terrestrial_only If `TRUE` (default), exclude fish, sharks and rays,
#'   marine mammals, sirenians, and pinnipeds. This is appropriate for a
#'   terrestrial predictor stack. Set `FALSE` only with predictors and a domain
#'   suitable for the additional taxa.
#' @param species_per_group Number of candidates selected systematically across
#'   the GBIF-count distribution within each group. `Inf` (default) retains all
#'   eligible species. A value such as `6L` creates a balanced pilot.
#' @param minimum_count Minimum regional GBIF count required before selection.
#' @param minimum_records Minimum valid, unique downloaded occurrences required
#'   for model fitting.
#' @param minimum_projected_species Minimum successfully projected species
#'   required before calculating metrics.
#' @param minimum_pd_groups Minimum rtrees groups with at least two projected
#'   species required for PD.
#' @param dist Buffer distance around occurrences in metres.
#' @param limit Maximum number of occurrence records downloaded per species.
#' @param retries Maximum GBIF download attempts per species.
#' @param categorical Character vector naming categorical predictor layers.
#' @param output_dir Root directory for projections, metrics, and audit files.
#' @param script Path of the generated targets script. Existing content at this
#'   path is replaced by [targets::tar_helper()].
#' @param store Dedicated targets data store for this workflow.
#' @param workers Number of compute workers.
#' @param gbif_workers Number of GBIF download workers.
#' @param reduce_workers Number of raster-reduction workers.
#' @param seed Reproducible targets seed used for background sampling and other
#'   stochastic work.
#' @param tree_index One-based posterior tree selected for rtrees groups that
#'   provide multiple megatrees.
#' @param projection_blocks_in_memory Memory-control value passed to
#'   [PredictSuitability()]. Larger values request smaller processing blocks.
#' @param metric_chunk_size Maximum number of species files opened in one
#'   richness or range-rarity reduction group.
#' @param pd_max_cells_per_block Maximum raster cells processed in one PD block.
#' @param error Global targets error mode. The default, `"null"`, permits the
#'   explicit status and audit targets to record branch exclusions.
#' @param plot If `TRUE`, open [targets::tar_visnetwork()] after the run.
#'
#' @return Invisibly, a list containing `script`, `store`, and `output_dir`.
#'
#' @examples
#' \dontrun{
#' run_workflow(
#'   file_path = "Clean_Taxa.csv",
#'   predictors = readRDS("Predictors/current_predictor_paths.rds"),
#'   country = "DK",
#'   groups = c(
#'     "plant", "bird", "mammal", "amphibian",
#'     "reptile", "bee", "butterfly"
#'   ),
#'   species_per_group = 6L,
#'   minimum_count = 20L,
#'   minimum_projected_species = 30L,
#'   categorical = "Landuse",
#'   script = "_TargetsDiversityPilot.R",
#'   store = "_targets_diversity_pilot"
#' )
#' }
#'
#' @importFrom targets tar_helper tar_make tar_option_set tar_target
#'   tar_visnetwork
#' @export
run_workflow <- function(
    file_path,
    predictors,
    country = NULL,
    shapefile = NULL,
    filter = NULL,
    groups = .workflow_terrestrial_groups,
    terrestrial_only = TRUE,
    species_per_group = Inf,
    minimum_count = 7L,
    minimum_records = 7L,
    minimum_projected_species = 2L,
    minimum_pd_groups = 1L,
    dist = 500,
    limit = 5000L,
    retries = 5L,
    categorical = "Landuse",
    output_dir = file.path("Results", "speciespoolr_workflow"),
    script = "_targets.R",
    store = "_targets",
    workers = 2L,
    gbif_workers = min(2L, workers),
    reduce_workers = 1L,
    seed = 20260830L,
    tree_index = 1L,
    projection_blocks_in_memory = 16L,
    metric_chunk_size = 50L,
    pd_max_cells_per_block = 20000L,
    error = "null",
    plot = TRUE) {
  if (!xor(!is.null(country), !is.null(shapefile))) {
    stop("Supply exactly one of `country` and `shapefile`.", call. = FALSE)
  }
  if (
    !is.character(file_path) ||
      length(file_path) != 1L ||
      is.na(file_path) ||
      !nzchar(file_path)
  ) {
    stop("`file_path` must be one non-empty path.", call. = FALSE)
  }
  predictors <- unique(as.character(predictors))
  if (length(predictors) == 0L || anyNA(predictors) || any(!nzchar(predictors))) {
    stop("`predictors` must contain one or more raster paths.", call. = FALSE)
  }

  groups <- unique(as.character(groups))
  unknown_groups <- setdiff(groups, .workflow_supported_groups)
  if (length(groups) == 0L || length(unknown_groups) > 0L) {
    stop(
      "Unsupported rtrees group(s): ",
      paste(unknown_groups, collapse = ", "),
      ".",
      call. = FALSE
    )
  }
  if (isTRUE(terrestrial_only)) {
    groups <- setdiff(groups, c("fish", "shark_ray"))
  }
  if (length(groups) == 0L) {
    stop("No groups remain after applying the workflow scope.", call. = FALSE)
  }
  if (
    !is.logical(terrestrial_only) ||
      length(terrestrial_only) != 1L ||
      is.na(terrestrial_only)
  ) {
    stop("`terrestrial_only` must be TRUE or FALSE.", call. = FALSE)
  }
  if (!is.null(categorical)) {
    categorical <- unique(as.character(categorical))
    if (anyNA(categorical) || any(!nzchar(categorical))) {
      stop(
        "`categorical` must contain non-empty layer names or be NULL.",
        call. = FALSE
      )
    }
  }

  workers <- .workflow_assert_scalar_integer(workers, "workers")
  gbif_workers <- .workflow_assert_scalar_integer(
    gbif_workers,
    "gbif_workers"
  )
  reduce_workers <- .workflow_assert_scalar_integer(
    reduce_workers,
    "reduce_workers"
  )
  seed <- .workflow_assert_scalar_integer(seed, "seed", minimum = 0L)
  minimum_count <- .workflow_assert_scalar_integer(
    minimum_count,
    "minimum_count",
    minimum = 0L
  )
  minimum_records <- .workflow_assert_scalar_integer(
    minimum_records,
    "minimum_records"
  )
  minimum_projected_species <- .workflow_assert_scalar_integer(
    minimum_projected_species,
    "minimum_projected_species"
  )
  minimum_pd_groups <- .workflow_assert_scalar_integer(
    minimum_pd_groups,
    "minimum_pd_groups"
  )
  limit <- .workflow_assert_scalar_integer(limit, "limit")
  retries <- .workflow_assert_scalar_integer(retries, "retries")
  tree_index <- .workflow_assert_scalar_integer(tree_index, "tree_index")
  projection_blocks_in_memory <- .workflow_assert_scalar_integer(
    projection_blocks_in_memory,
    "projection_blocks_in_memory"
  )
  metric_chunk_size <- .workflow_assert_scalar_integer(
    metric_chunk_size,
    "metric_chunk_size",
    minimum = 2L
  )
  pd_max_cells_per_block <- .workflow_assert_scalar_integer(
    pd_max_cells_per_block,
    "pd_max_cells_per_block"
  )
  if (
    !is.numeric(dist) ||
      length(dist) != 1L ||
      is.na(dist) ||
      !is.finite(dist) ||
      dist <= 0
  ) {
    stop("`dist` must be one positive distance in metres.", call. = FALSE)
  }
  if (
    !is.infinite(species_per_group) &&
      (
        !is.numeric(species_per_group) ||
          length(species_per_group) != 1L ||
          is.na(species_per_group) ||
          species_per_group != floor(species_per_group) ||
          species_per_group < 1L
      )
  ) {
    stop("`species_per_group` must be a positive integer or Inf.", call. = FALSE)
  }

  filter_expression <- substitute(filter)
  if (
    is.call(filter_expression) &&
      identical(filter_expression[[1L]], quote(quote))
  ) {
    filter_expression <- filter_expression[[2L]]
  } else {
    evaluated_filter <- tryCatch(
      eval(filter_expression, envir = parent.frame()),
      error = function(e) NULL
    )
    if (
      is.call(evaluated_filter) ||
        is.name(evaluated_filter) ||
        is.logical(evaluated_filter)
    ) {
      filter_expression <- evaluated_filter
    }
  }
  if (identical(filter_expression, quote(NULL))) {
    filter_expression <- quote(TRUE)
  }

  projection_output_root <- file.path(output_dir, "species_projections")
  metric_output_root <- file.path(output_dir, "metrics")
  audit_output_root <- file.path(output_dir, "audits")

  Taxa_file <- Study_area_file <- Data <- NULL
  Count_Presences <- Eligible_taxa <- Selected_taxa <- Species <- NULL
  Presences_raw <- Valid_Presences <- Presence_audit <- NULL
  Presence_audit_file <- Species_file_index <- Current_predictors <- NULL
  Buffer <- SpeciesModels <- NULL
  Model_audit <- Current_species_products <- Current_summary <- NULL
  Current_status_files <- Current_status <- Projection_audit <- NULL
  Projection_exclusions <- Current_paths <- Projected_taxa <- NULL
  Metric_groups <- Group_taxa <- Group_paths <- Phylo_tree <- NULL
  Tree_coverage <- Tree_coverage_file <- Richness_all_file <- NULL
  Richness_group_file <- Range_weights <- Range_weights_file <- NULL
  RangeRarity_all_file <- RangeRarity_group_file <- PD_group_file <- NULL
  PD_group_stats <- PD_group_stats_file <- Projection_audit_file <- NULL
  Selection_file <- Selection_audit_file <- Workflow_audit <- NULL
  Workflow_audit_file <- map <- rtrees_group <- NULL

  targets::tar_helper(
    path = script,
    code = {
      Sys.setenv(
        OMP_NUM_THREADS = "1",
        OPENBLAS_NUM_THREADS = "1",
        MKL_NUM_THREADS = "1",
        VECLIB_MAXIMUM_THREADS = "1"
      )

      controller_compute <- crew::crew_controller_local(
        name = "compute",
        workers = !!workers,
        tasks_max = 50L
      )
      controller_gbif <- crew::crew_controller_local(
        name = "gbif",
        workers = !!gbif_workers
      )
      controller_reduce <- crew::crew_controller_local(
        name = "reduce",
        workers = !!reduce_workers
      )
      controller_tree <- crew::crew_controller_local(
        name = "tree",
        workers = 1L
      )

      targets::tar_option_set(
        packages = c(
          "SpeciesPoolR",
          "crew",
          "dplyr",
          "readr",
          "terra"
        ),
        error = !!error,
        seed = !!seed,
        garbage_collection = 1,
        controller = crew::crew_controller_group(
          controller_compute,
          controller_gbif,
          controller_reduce,
          controller_tree
        ),
        resources = targets::tar_resources(
          crew = targets::tar_resources_crew(controller = "compute")
        )
      )

      study_area_target <- if (is.null(!!shapefile)) {
        targets::tar_target(Study_area_file, NULL)
      } else {
        targets::tar_target(
          Study_area_file,
          !!shapefile,
          format = "file"
        )
      }

      list(
        targets::tar_target(Taxa_file, !!file_path, format = "file"),
        targets::tar_target(
          Current_predictors,
          !!predictors,
          format = "file"
        ),
        study_area_target,
        targets::tar_target(
          Data,
          {
            out <- SpeciesPoolR:::.workflow_prepare_taxa(Taxa_file)
            out <- dplyr::filter(out, !!filter_expression)
            SpeciesPoolR:::.workflow_apply_scope(
              out,
              groups = !!groups,
              terrestrial_only = !!terrestrial_only
            )
          }
        ),
        targets::tar_target(
          Count_Presences,
          SpeciesPoolR::count_presences_simple(
            Data,
            country = !!country,
            shapefile = Study_area_file,
            retries = !!retries,
            verbose = TRUE
          )
        ),
        targets::tar_target(
          Eligible_taxa,
          {
            counts <- as.data.frame(Count_Presences)
            counts <- counts[!duplicated(counts$species), c("species", "N")]
            out <- dplyr::inner_join(Data, counts, by = "species")
            out <- out[
              is.finite(out$N) & out$N >= !!minimum_count,
              ,
              drop = FALSE
            ]
            out[order(out$rtrees_group, out$N, out$species), , drop = FALSE]
          }
        ),
        targets::tar_target(
          Selected_taxa,
          {
            out <- SpeciesPoolR:::.workflow_systematic_group_sample(
              Eligible_taxa,
              groups = !!groups,
              number_per_group = !!species_per_group
            )
            if (nrow(out) < !!minimum_projected_species) {
              stop(
                "Only ", nrow(out),
                " candidate species were selected; at least ",
                !!minimum_projected_species, " are required.",
                call. = FALSE
              )
            }
            out
          }
        ),
        targets::tar_target(
          Selection_file,
          {
            path <- file.path(
              !!audit_output_root,
              "selected_taxa.csv"
            )
            dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
            readr::write_csv(Selected_taxa, path)
            path
          },
          format = "file"
        ),
        targets::tar_target(
          Selection_audit_file,
          {
            available <- dplyr::count(
              Eligible_taxa,
              rtrees_group,
              name = "eligible_species"
            )
            selected <- dplyr::count(
              Selected_taxa,
              rtrees_group,
              name = "selected_species"
            )
            audit <- dplyr::full_join(
              available,
              selected,
              by = "rtrees_group"
            )
            audit$eligible_species[is.na(audit$eligible_species)] <- 0L
            audit$selected_species[is.na(audit$selected_species)] <- 0L
            path <- file.path(
              !!audit_output_root,
              "selection_audit.csv"
            )
            dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
            readr::write_csv(audit, path)
            path
          },
          format = "file"
        ),
        targets::tar_target(
          Species,
          Selected_taxa$species,
          iteration = "vector"
        ),
        targets::tar_target(
          Presences_raw,
          SpeciesPoolR:::.workflow_get_presences_with_retry(
            Species,
            country = !!country,
            shapefile = Study_area_file,
            limit = !!limit,
            retries = !!retries
          ),
          pattern = map(Species),
          iteration = "list",
          error = "null",
          resources = targets::tar_resources(
            crew = targets::tar_resources_crew(controller = "gbif")
          )
        ),
        targets::tar_target(
          Valid_Presences,
          {
            out <- SpeciesPoolR:::.workflow_validate_presence_branches(
              Presences_raw,
              Species,
              minimum_records = !!minimum_records
            )
            if (length(out) < !!minimum_projected_species) {
              stop(
                "Only ", length(out),
                " species retained valid occurrence data; at least ",
                !!minimum_projected_species, " are required.",
                call. = FALSE
              )
            }
            out
          },
          iteration = "list"
        ),
        targets::tar_target(
          Presence_audit,
          SpeciesPoolR:::.workflow_presence_audit(
            Presences_raw,
            Species,
            Valid_Presences,
            Selected_taxa
          )
        ),
        targets::tar_target(
          Species_file_index,
          SpeciesPoolR:::.workflow_species_file_index(
            names(Valid_Presences)
          )
        ),
        targets::tar_target(
          Presence_audit_file,
          {
            path <- file.path(
              !!audit_output_root,
              "presence_audit.csv"
            )
            dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
            readr::write_csv(Presence_audit, path)
            path
          },
          format = "file"
        ),
        geotargets::tar_terra_vect(
          Buffer,
          SpeciesPoolR::make_buffer(Valid_Presences, dist = !!dist),
          pattern = map(Valid_Presences)
        ),
        targets::tar_target(
          SpeciesModels,
          SpeciesPoolR::FitSpeciesModels(
            Valid_Presences,
            file = Current_predictors,
            categorical = !!categorical
          ),
          pattern = map(Valid_Presences),
          iteration = "list"
        ),
        targets::tar_target(
          Model_audit,
          SpeciesPoolR::summarise_model_branches(SpeciesModels)
        ),
        targets::tar_target(
          Current_species_products,
          {
            Species_file_index
            SpeciesPoolR:::.workflow_project_current_species(
              models = SpeciesModels,
              presences = Valid_Presences,
              buffer = Buffer,
              predictors = Current_predictors,
              categorical = !!categorical,
              output_root = !!projection_output_root,
              blocks_in_memory = !!projection_blocks_in_memory,
              minimum_complete_presences = !!minimum_records
            )
          },
          pattern = map(SpeciesModels, Valid_Presences, Buffer),
          iteration = "list",
          format = "file",
          retrieval = "worker"
        ),
        targets::tar_target(
          Current_summary,
          SpeciesPoolR:::.workflow_read_projection_summaries(
            Current_species_products
          )
        ),
        targets::tar_target(
          Current_status_files,
          SpeciesPoolR:::.workflow_collect_product_files(
            Current_species_products,
            "_status.csv"
          ),
          format = "file"
        ),
        targets::tar_target(
          Current_status,
          SpeciesPoolR::read_projection_status(Current_status_files)
        ),
        targets::tar_target(
          Projection_audit,
          SpeciesPoolR::make_projection_audit(
            valid_presences = Valid_Presences,
            model_audit = Model_audit,
            current_summary = Current_summary,
            scenarios = character(),
            projection_statuses = Current_status
          )
        ),
        targets::tar_target(
          Projection_exclusions,
          SpeciesPoolR::projection_exclusions(Projection_audit)
        ),
        targets::tar_target(
          Projection_audit_file,
          {
            path <- file.path(
              !!audit_output_root,
              "projection_audit.csv"
            )
            dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
            readr::write_csv(Projection_audit, path)
            path
          },
          format = "file"
        ),
        targets::tar_target(
          Current_paths,
          SpeciesPoolR::select_projection_paths(
            projection_summary = Current_summary,
            model_audit = Model_audit,
            scenario = "current",
            exclusions = Projection_exclusions
          )
        ),
        targets::tar_target(
          Projected_taxa,
          {
            out <- Selected_taxa[
              Selected_taxa$species %in% names(Current_paths),
              ,
              drop = FALSE
            ]
            out$binary_path <- unname(Current_paths[
              match(out$species, names(Current_paths))
            ])
            if (nrow(out) < !!minimum_projected_species) {
              stop(
                "Only ", nrow(out),
                " species projected successfully; at least ",
                !!minimum_projected_species, " are required.",
                call. = FALSE
              )
            }
            out
          }
        ),
        targets::tar_target(
          Metric_groups,
          {
            counts <- table(Projected_taxa$rtrees_group)
            groups_with_trees <- names(counts)[counts >= 2L]
            if (length(groups_with_trees) < !!minimum_pd_groups) {
              stop(
                "Only ", length(groups_with_trees),
                " rtrees groups retained at least two projected species; ",
                "at least ", !!minimum_pd_groups, " are required.",
                call. = FALSE
              )
            }
            sort(groups_with_trees)
          },
          iteration = "vector"
        ),
        targets::tar_target(
          Group_taxa,
          Projected_taxa[
            Projected_taxa$rtrees_group == Metric_groups,
            c(
              "species",
              "genus",
              "family",
              "rtrees_group",
              "N",
              "binary_path"
            ),
            drop = FALSE
          ],
          pattern = map(Metric_groups),
          iteration = "list"
        ),
        targets::tar_target(
          Group_paths,
          stats::setNames(Group_taxa$binary_path, Group_taxa$species),
          pattern = map(Group_taxa),
          iteration = "list"
        ),
        targets::tar_target(
          Phylo_tree,
          SpeciesPoolR::build_rtrees_tree(
            species = Group_taxa[, c("species", "genus", "family")],
            group = Metric_groups,
            tree_index = !!tree_index,
            scenario = "at_basal_node",
            show_grafted = FALSE,
            progress = "none"
          ),
          pattern = map(Group_taxa, Metric_groups),
          iteration = "list",
          resources = targets::tar_resources(
            crew = targets::tar_resources_crew(controller = "tree")
          )
        ),
        targets::tar_target(
          Tree_coverage,
          {
            out <- SpeciesPoolR::audit_tree_coverage(
              species = Group_taxa$species,
              Tree = Phylo_tree,
              group = Metric_groups
            )
            if (any(!out$matched)) {
              stop(
                "Tree coverage is incomplete for `", Metric_groups, "`: ",
                paste(out$species[!out$matched], collapse = ", "),
                call. = FALSE
              )
            }
            out
          },
          pattern = map(Group_taxa, Phylo_tree, Metric_groups),
          iteration = "list"
        ),
        targets::tar_target(
          Tree_coverage_file,
          {
            path <- file.path(
              !!audit_output_root,
              "tree_coverage.csv"
            )
            dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
            readr::write_csv(dplyr::bind_rows(Tree_coverage), path)
            path
          },
          format = "file"
        ),
        targets::tar_target(
          Richness_all_file,
          {
            path <- file.path(!!metric_output_root, "Richness_all.tif")
            result <- SpeciesPoolR::sum_binary_files_tree(
              paths = Current_paths,
              predictors = Current_predictors,
              filename = path,
              name = "Richness_all",
              chunk_size = !!metric_chunk_size
            )
            SpeciesPoolR:::.workflow_raster_output_path(result, path)
          },
          format = "file",
          resources = targets::tar_resources(
            crew = targets::tar_resources_crew(controller = "reduce")
          )
        ),
        targets::tar_target(
          Richness_group_file,
          {
            path <- file.path(
              !!metric_output_root,
              paste0("Richness_", Metric_groups, ".tif")
            )
            result <- SpeciesPoolR::sum_binary_files_tree(
              paths = Group_paths,
              predictors = Current_predictors,
              filename = path,
              name = paste0("Richness_", Metric_groups),
              chunk_size = !!metric_chunk_size
            )
            SpeciesPoolR:::.workflow_raster_output_path(result, path)
          },
          pattern = map(Group_paths, Metric_groups),
          iteration = "vector",
          format = "file",
          resources = targets::tar_resources(
            crew = targets::tar_resources_crew(controller = "reduce")
          )
        ),
        targets::tar_target(
          Range_weights,
          SpeciesPoolR::calc_range_weights_files(
            paths = Current_paths,
            template = Current_predictors,
            unit = "km2",
            align = "error",
            verbose = TRUE
          ),
          resources = targets::tar_resources(
            crew = targets::tar_resources_crew(controller = "reduce")
          )
        ),
        targets::tar_target(
          Range_weights_file,
          {
            path <- file.path(
              !!audit_output_root,
              "range_weights.csv"
            )
            dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
            readr::write_csv(Range_weights, path)
            path
          },
          format = "file"
        ),
        targets::tar_target(
          RangeRarity_all_file,
          {
            path <- file.path(
              !!metric_output_root,
              "RangeRarity_all.tif"
            )
            result <- SpeciesPoolR::calc_range_rarity_files(
              paths = Current_paths,
              Weights = Range_weights,
              template = Current_predictors,
              filename = path,
              name = "RangeRarity_all",
              output = "cell_contribution",
              chunk_size = !!metric_chunk_size,
              align = "error",
              verbose = TRUE
            )
            SpeciesPoolR:::.workflow_raster_output_path(result, path)
          },
          format = "file",
          resources = targets::tar_resources(
            crew = targets::tar_resources_crew(controller = "reduce")
          )
        ),
        targets::tar_target(
          RangeRarity_group_file,
          {
            path <- file.path(
              !!metric_output_root,
              paste0("RangeRarity_", Metric_groups, ".tif")
            )
            result <- SpeciesPoolR::calc_range_rarity_files(
              paths = Group_paths,
              Weights = Range_weights,
              template = Current_predictors,
              filename = path,
              name = paste0("RangeRarity_", Metric_groups),
              output = "cell_contribution",
              chunk_size = !!metric_chunk_size,
              align = "error",
              verbose = TRUE
            )
            SpeciesPoolR:::.workflow_raster_output_path(result, path)
          },
          pattern = map(Group_paths, Metric_groups),
          iteration = "vector",
          format = "file",
          resources = targets::tar_resources(
            crew = targets::tar_resources_crew(controller = "reduce")
          )
        ),
        targets::tar_target(
          PD_group_file,
          {
            path <- file.path(
              !!metric_output_root,
              paste0("PD_", Metric_groups, ".tif")
            )
            result <- SpeciesPoolR::calc_pd_files(
              paths = Group_paths,
              Tree = Phylo_tree,
              template = Current_predictors,
              filename = path,
              name = paste0("PD_", Metric_groups),
              include_root = FALSE,
              unmatched = "error",
              align = "error",
              max_cells_per_block = !!pd_max_cells_per_block,
              verbose = TRUE
            )
            SpeciesPoolR:::.workflow_raster_output_path(result, path)
          },
          pattern = map(Group_paths, Phylo_tree, Metric_groups),
          iteration = "vector",
          format = "file",
          resources = targets::tar_resources(
            crew = targets::tar_resources_crew(controller = "reduce")
          )
        ),
        targets::tar_target(
          PD_group_stats,
          {
            raster_stats <- terra::global(
              terra::rast(PD_group_file),
              fun = c("min", "mean", "max", "sum"),
              na.rm = TRUE
            )
            data.frame(
              rtrees_group = Metric_groups,
              species = nrow(Group_taxa),
              min = raster_stats$min[[1L]],
              mean = raster_stats$mean[[1L]],
              max = raster_stats$max[[1L]],
              sum = raster_stats$sum[[1L]],
              file = PD_group_file,
              stringsAsFactors = FALSE
            )
          },
          pattern = map(PD_group_file, Metric_groups, Group_taxa),
          iteration = "list"
        ),
        targets::tar_target(
          PD_group_stats_file,
          {
            path <- file.path(
              !!audit_output_root,
              "pd_group_stats.csv"
            )
            dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
            readr::write_csv(dplyr::bind_rows(PD_group_stats), path)
            path
          },
          format = "file"
        ),
        targets::tar_target(
          Workflow_audit,
          {
            richness_stats <- terra::global(
              terra::rast(Richness_all_file),
              fun = c("min", "mean", "max"),
              na.rm = TRUE
            )
            rarity_stats <- terra::global(
              terra::rast(RangeRarity_all_file),
              fun = c("min", "mean", "max", "sum"),
              na.rm = TRUE
            )
            positive_ranges <- sum(
              is.finite(Range_weights$range_size) &
                Range_weights$range_size > 0
            )
            rarity_difference <-
              rarity_stats$sum[[1L]] - positive_ranges
            coverage <- dplyr::bind_rows(Tree_coverage)

            data.frame(
              selected_candidates = nrow(Selected_taxa),
              valid_presence_species = length(Valid_Presences),
              successful_models = sum(Model_audit$model_ok, na.rm = TRUE),
              projected_species = length(Current_paths),
              rtrees_groups = length(unique(Projected_taxa$rtrees_group)),
              pd_groups = length(Metric_groups),
              complete_tree_coverage = all(coverage$matched),
              richness_min = richness_stats$min[[1L]],
              richness_mean = richness_stats$mean[[1L]],
              richness_max = richness_stats$max[[1L]],
              positive_range_species = positive_ranges,
              total_range_rarity_contribution = rarity_stats$sum[[1L]],
              range_rarity_difference = rarity_difference,
              range_rarity_identity_ok = abs(rarity_difference) <=
                1e-6 * max(1, positive_ranges),
              pd_group_rasters = length(PD_group_file),
              richness_group_rasters = length(Richness_group_file),
              rarity_group_rasters = length(RangeRarity_group_file),
              stringsAsFactors = FALSE
            )
          }
        ),
        targets::tar_target(
          Workflow_audit_file,
          {
            path <- file.path(
              !!audit_output_root,
              "workflow_audit.csv"
            )
            dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
            readr::write_csv(Workflow_audit, path)
            path
          },
          format = "file"
        )
      )
    },
    tidy_eval = TRUE
  )

  targets::tar_make(script = script, store = store)
  if (isTRUE(plot)) {
    targets::tar_visnetwork(script = script, store = store)
  }

  invisible(list(
    script = script,
    store = store,
    output_dir = output_dir
  ))
}
